name: NextGens
version: '${project.version}'
main: com.muhammaddaffa.nextgens.NextGens
api-version: 1.13
authors: [aglerr]
description: A next generation gens tycoon plugin
website: https://muhammaddaffa.com
load: POSTWORLD
depend: [Vault, PlaceholderAPI]
softdepend:
  - MyWorlds
  - Multiverse-Core
  - BentoBox
  - HolographicDisplays
  - DecentHolograms
  - SuperiorSkyblock2
  - ShopGUIPlus
  - WildTools
  - DeluxeSellwands
  - LWC
  - AdvancedChests
  - FabledSkyblock
  - ItemsAdder
  - AxBoosters
  - Bolt
  - Slimefun
  - ModelEngine